name: "Terraform Destroy"

on:
    push:
      branches:
        - main

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ter_files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Remove S3 and DynamoDB from State
        id: state-rm
        run: |
          terraform state rm aws_s3_bucket.backend_bucket
          terraform state rm aws_dynamodb_table.backend_table

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
